#!/usr/bin/env node
/**
 * build-data.mjs
 * -----------------------------------------------------------------------------
 * Bundles books-data.json + covers.json + goodreads.json into
 * assets/site-data.js so the pages can load everything with a plain <script>
 * tag — which means the site works when you just double-click index.html,
 * with no local server needed.
 *
 * Run this whenever you edit books-data.json:
 *   node tools/build-data.mjs
 *
 * (fetch-covers.mjs and fetch-goodreads.mjs both run this for you automatically
 * at the end.)
 * -----------------------------------------------------------------------------
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const root = (p) => join(HERE, "..", p);

const readJson = (p) => (existsSync(root(p)) ? JSON.parse(readFileSync(root(p), "utf8")) : {});

const books = JSON.parse(readFileSync(root("books-data.json"), "utf8"));
const covers = readJson("covers.json");
const goodreads = readJson("goodreads.json");

const banner =
  "/* AUTO-GENERATED by tools/build-data.mjs — do not edit by hand.\n" +
  "   Edit books-data.json instead, then re-run: node tools/build-data.mjs */\n";

const payload = {
  generatedAt: new Date().toISOString(),
  books,
  covers,
  goodreads,
};

writeFileSync(
  root("assets/site-data.js"),
  banner + "window.SITE_DATA = " + JSON.stringify(payload) + ";\n"
);

const bookCount = books.categories.reduce((n, c) => n + c.books.length, 0);
console.log(
  `Wrote assets/site-data.js — ${books.categories.length} categories, ` +
    `${bookCount} book entries, ${Object.keys(covers).length} covers, ` +
    `${Object.keys(goodreads).length} Goodreads links.`
);
